export const SET_SPEECH_BOX_EXPANDED_STATE: string = 'SET_SPEECH_BOX_EXPANDED_STATE'
export const START_API_CALL: string = 'START_API_CALL'
export const API_CALL_SUCCESS: string = 'API_CALL_SUCCESS'
export const API_CALL_FAILURE: string = 'API_CALL_FAILURE'